Added more tests
Added script that exhaustively tests for sparsity for a range of k and
l.

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -1,10 +1,16 @@
 #!/bin/bash
 #
-# Run tests for Laman plugin.
+# Run tests against known sequences.
 
 GREEN='\033[0;32m'
 RED='\033[0;31m'
 NC='\033[0m'
+
+if [ ! -f geng ]
+then
+    printf "${RED}FAILED${NC}\tPlease compile geng before running these tests\n"
+    exit 1
+fi
 
 fails=0
 
@@ -88,7 +94,8 @@ test -K1
 echo
 
 
-if [ $fails -eq 0 ] ; then
+if [ $fails -eq 0 ]
+then
    printf "${GREEN}PASSED ALL TESTS${NC}\n\n"
    exit 0
 else
